name: idealized_modeling

channels: 
  - conda-forge
dependencies:
  - python<3.11
  - jupyter
  - jupytext
  - fortran-compiler
  - c-compiler
  - numpy
  - scipy
  - pandas
  - matplotlib
  - cbsyst
  - pip
  - pip:
    - git+https://github.com/atmtools/climt@rrtmg-only
    - konrad
